#!/bin/bash
cd /tmp/rom # Depends on where source got synced

# Normal build steps
. build/envsetup.sh
lunch potato_begonia-userdebug
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 20G # It took only 6.4GB for mido
ccache -o compression=true # Will save times and data to download and upload ccache, also negligible performance issue
ccache -z # Clear old stats, so monitor script will provide real ccache statistics

# Next 8 lines should be run first to collect ccache and then upload, after doning it 1 or 2 times, our ccache will help to build without these 8 lines
make api-stubs-docs || echo no problem, we need ccache
make hiddenapi-lists-docs || echo no problem, we need ccache
make system-api-stubs-docs || echo no problem we need ccache
make test-api-stubs-docs || echo no problem, we need ccache
make potato -j23 & # dont remove that '&'
sleep 85m
kill %1
ccache -s
#and dont use below codes for first 1 or 2 times, to get ccache uploaded,



# Build command! j10 for 10 cpu, j8 for 8 cpu, otherwise memeroy will end up even its 24G
# Upload rom zip file if succeed to build! Send notification to tg! And send shell to tg if build fails!

#Let's compile by parts! Coz of ram issue!
#make api-stubs-docs -j16 || echo no problem
#make hiddenapi-lists-docs -j16 || echo no problem
#make system-api-stubs-docs -j16 || echo no problem
#make test-api-stubs-docs -j16 || echo no problem
#make potato -j16 
#ccache -s # Let's print ccache statistics finally
#time rclone  copy out/target/product/begonia/potato_begonia-11* onedrive:/begonia/potato/ -P
