#!/bin/bash

mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init -q --no-repo-verify --depth=1 -u git://github.com/PotatoProject/manifest.git -b lineage-17.1 -g default,-device,-mips,-darwin,-notdefault

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 30 || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 8

git clone https://github.com/LineageOS/android_device_mediatek_sepolicy device/mediatek/sepolicy
git clone https://github.com/LineageOS/android_hardware_mediatek hardware/mediatek
git clone https://github.com/HyperTeam/proprietary_vendor_firmware vendor/firmware
git clone https://github.com/LineageOS/android_device_xiaomi_mt6785-common device/xiaomi/mt6785-common
git clone https://github.com/LineageOS/android_kernel_xiaomi_mt6785 kernel/xiaomi/mt6785
git clone https://github.com/LineageOS/android_device_xiaomi_begoniain device/xiaomi/begoniain
git clone https://gitlab.com/the-muppets/proprietary_vendor_xiaomi -b lineage-17.1 vendor/xiaomi
